<%@ Page Language="C#" AutoEventWireup="true"  EnableEventValidation="false" CodeFile="My Bookings.aspx.cs" Inherits="_Default" %>
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="ajaxToolkit" %>
<%@ Register Assembly="System.Web.DataVisualization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" Namespace="System.Web.UI.DataVisualization.Charting" TagPrefix="asp" %>

<!DOCTYPE html>
<html>
<head runat="server">
<title>CRB Portal</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Raleway", Arial, Helvetica, sans-serif}
.mySlides {display: none}
</style>
<script type="text/javascript"  lang="Javascript">
     function DisableBackButton() {
       window.history.forward()
      }
     DisableBackButton();
     window.onload = DisableBackButton;
     window.onpageshow = function(evt) { if (evt.persisted) DisableBackButton() }
     window.onunload = function() { void (0) }
 </script>
</head>

<body  runat="server">
<form runat="server">     
<asp:ScriptManager ID="ScriptManager1" runat="server"></asp:ScriptManager>



<!-- Sidebar/menu -->
<nav class=" w3-light-grey " style="z-index:0;width:292px; left: 0px;position:fixed;margin-top:50px" id="mySidebar">             
<div class="w3-container w3-disaply-container" >
      <p><label><i class="fa fa-id-badge"></i> Ps. No</label></p>
      <asp:TextBox ID="txtno" class="w3-input w3-border" runat="server"   ReadOnly="true"></asp:TextBox>     
      <p><label><i class="fa fa-user-circle"></i> Name</label></p>
      <asp:TextBox ID="TextBox4"  runat="server"  class="w3-input w3-border" ReadOnly="true"></asp:TextBox>  
      <p><label><i class="fa fa-envelope"></i> E-mail</label></p> 
      <asp:TextBox ID="TextBox5"  runat="server" class="w3-input w3-border" ReadOnly="true"></asp:TextBox>

<hr />
<hr />
<hr />
<hr />
<hr />
<hr />
<hr />
<hr />
<hr />
<hr />
<hr />
<hr />
<hr />
<hr />
<hr />
<hr />
<hr />


    <p><asp:button runat="server" Text="Checkings"  class=" w3-button w3-block w3-yellow w3-left-justify" OnClick="Unnamed_Click"  ></asp:button></p>     
    <p><asp:button runat="server" Text="Home"  class=" w3-button w3-block w3-green w3-left-justify" OnClick="Unnamed_Click2" PostBackUrl="~/Default3.aspx" ></asp:button></p>     
    <p><asp:button runat="server" Text="Logout"  class=" w3-button w3-block  w3-left-justify" OnClick="Unnamed_Click1" PostBackUrl="~/Login.aspx"></asp:button></p>

<hr />   
</div>  
</nav>



<!-- Slideshow Header -->
<div class="w3-bar w3-top w3-white w3-card">
<a class="w3-text-blue w3-left w3-padding-large"  >Conference Room Booking Portal  </a>
</div>


<!-- My Bookings-->
<div  class="w3-card" style="margin-left:298px;position:fixed;width:1438px;margin-top:50px;height:93.5%" runat="server">
<asp:UpdatePanel ID="UpdatePanel1" runat="server">
<ContentTemplate>
 <div class="w3-full" >
            <p><a class="w3-text-red w3-padding" style="align-content:center;font-size:medium"  >MY BOOKINGS</a></p>
            </div>
<div  class="w3-middle" style="margin-left:270px;margin-top:9.50%;margin-bottom:33%">
<table class="table table-bordered" cellspacing="0" rules="all" border="1" id="ContentPlaceHolder1_GridView1" >	
<asp:GridView ID="GridView1" DataKeyNames="eid" runat="server" CellPadding="4" AllowPaging="True" PageSize="5" BackColor="White" BorderColor="#3366CC" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" OnPageIndexChanging="GridView1_PageIndexChanging"
GridLines="Both"    AutoGenerateDeleteButton="True"  OnRowDataBound="GridView1_RowDataBound1"  OnRowDeleting="GridView1_RowDeleting1">
    
</asp:GridView>	
</table>  	
</div> 
    

</div>
</ContentTemplate>
</asp:UpdatePanel>  
<div  class="w3-row-padding" ><p style="color:black;margin-top:48.5%;position:fixed;margin-left:64.5%;margin-bottom:1.5%"   >© 2019. All Rights Reserved | Design by: Under Internship in LTHE Onshore IT, Baroda</p></div>                       
</div>

</form>
</body>
</html>



